import fitz
import os
import re

def sanitize_filename(filename):
    # Remove characters that are not allowed in filenames
    sanitized = re.sub(r'[\\/*?:"<>|]', "", filename)
    # Replace spaces with underscores and keep Vietnamese characters correctly
    return sanitized.strip()


import sys
from pathlib import Path

# Fix relative imports so we can load PDFVisionReader
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from server_support.pdf_vision_reader import PDFVisionReader

def find_manual_sections(pdf_path):
    sections = []
    try:
        # Utilize Pathway's native PDFVisionReader with automatic Azure GPT fallback
        reader = PDFVisionReader()
        
        # We only need the first 15 pages to find the TOC securely
        print("  [INFO] Analysing TOC via natively integrated PDFVisionReader...")
        result = reader.extract(pdf_path, pages=range(1, 15))
        
        # Iterate over the cleanly extracted vision/pymupdf text
        toc_start_page = None
        for pr in result.pages:
            text_upper = pr.text.upper()
            # Handle OCR misses like "MỤC  ỤC" instead of "MỤC LỤC"
            if any(kw in text_upper for kw in ["MỤC LỤC", "MỤC LỤC", "MỤC  LỤC", "MUC LUC", "MỤC  ỤC", "MUC UC"]):
                toc_start_page = pr.page_num
                print(f"  [INFO] Manual TOC visually detected on Page {toc_start_page}")
                break
                
        if toc_start_page is not None:
             print(f"  [INFO] Forcing Vision API on TOC pages {toc_start_page}-{toc_start_page+2} to guarantee table structure...")
             vision_result = reader.extract(pdf_path, pages=[toc_start_page, toc_start_page+1, toc_start_page+2], force_vision=True)
             full_toc_text = vision_result.full_text
             
             # Attempt to parse Markdown tables generated by Vision Output
             # e| Tên Bệnh | Trang |
             matches_md = re.finditer(r"\|\s*([^|\n]+?)\s*\|\s*(\d+)\s*\|", full_toc_text)
             for m in matches_md:
                 title = m.group(1).strip()
                 page_num = int(m.group(2))
                 # Filter out header rows
                 if len(title) > 5 and not title.isdigit() and "Trang" not in title and "Mục" not in title:
                     sections.append({'title': title, 'page': page_num})
             
             # Fallback to parse standard dotted layouts if no Markdown table was detected
             if len(sections) == 0:
                 matches_dots = re.finditer(r"([A-Z0-9\sÀÁÂÃÈÉÊÌÍÒÓÔÕÙÚÝàáâãèéêìíòóôõùúýĂăĐđĨĩŨũƠơƯưẠ-ỹ,()]+?)\s*\.{3,}\s*(\d+)", full_toc_text)
                 for m in matches_dots:
                     title = m.group(1).strip().strip('.')
                     page_num = int(m.group(2))
                     if len(title) > 5 and not title.isdigit():
                         sections.append({'title': title, 'page': page_num})
             
             # Second fallback for TMH where PyMuPDF or Vision drops dots and outputs line-by-line
             if len(sections) == 0:
                  # This parses: [Title] \n [PageNumber]
                  lines = [line.strip() for line in full_toc_text.split('\n') if line.strip()]
                  for idx, line in enumerate(lines):
                       if line.isdigit() and idx > 0:
                            title = lines[idx-1].strip()
                            page_num = int(line)
                            if len(title) > 5 and not title.isdigit() and "Trang" not in title:
                                 sections.append({'title': title, 'page': page_num})
                    
        # Optional: Print summary of Vision invocation
        summary = result.summary()
        if summary.get('vision_enhanced_pages', 0) > 0:
            print(f"  [METRIC] Vision invoked for {summary['vision_enhanced_pages']} garbled pages.")
    except Exception as e:
        print(f"  [ERR] PDFVisionReader failed on {pdf_path}: {e}")
    return sections

def split_pdf(source_pdf, output_dir):
    print(f"\nProcessing: {source_pdf}")
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)
        
    doc = fitz.open(source_pdf)
    toc = doc.get_toc()
    
    sections = []
    if toc:
        print("  [INFO] Internal TOC found. Extraction Level 1 items.")
        for item in toc:
            if item[0] == 1:
                sections.append({'title': item[1], 'page': item[2]})
    else:
        print("  [INFO] No internal TOC. Attempting manual TOC extraction via pdfplumber...")
        sections = find_manual_sections(source_pdf)

    if not sections:
        print(f"  [WARN] Failed to identify sections in {os.path.basename(source_pdf)}.")
        return 0

    print(f"  Target: {len(sections)} sections identified.")
    
    count = 0
    # Sort sections by page number to ensure ranges are correct
    sections.sort(key=lambda x: x['page'])
    
    for i in range(len(sections)):
        start_page = sections[i]['page'] - 1
        if i + 1 < len(sections):
            end_page = sections[i+1]['page'] - 2
        else:
            end_page = len(doc) - 1
            
        if start_page < 0 or start_page > end_page:
            continue
            
        # Limit title length for filename
        raw_title = sections[i]['title'][:100]
        disease_name = sanitize_filename(raw_title)
        output_filename = os.path.join(output_dir, f"{disease_name}.pdf")
        
        try:
            new_doc = fitz.open()
            new_doc.insert_pdf(doc, from_page=start_page, to_page=end_page)
            new_doc.save(output_filename)
            new_doc.close()
            count += 1
            print(f"  [SAVED] {start_page+1}-{end_page+1}: {disease_name}.pdf")
        except Exception as e:
            print(f"  [ERR] Failed to save {disease_name}: {e}")

    doc.close()
    return count

def main():
    base_dir = r"D:\desktop_folder\01_claudecodeleak\roadmap_master_data"
    output_base_dir = os.path.join(base_dir, "Extracted_Protocols")
    
    pdfs = [
        "Phác đồ hen phế quản.pdf",
        "Phác đồ hô hấp.pdf",
        "Phác đồ tai mũi họng.pdf",
        "Phác đồ viêm phổi.pdf"
    ]
    
    total_split = 0
    for pdf_name in pdfs:
        full_path = os.path.join(base_dir, pdf_name)
        if os.path.exists(full_path):
            category_dir = os.path.join(output_base_dir, pdf_name.replace(".pdf", ""))
            split_count = split_pdf(full_path, category_dir)
            total_split += split_count
        else:
            print(f"File not found: {full_path}")
            
    print(f"\nCompleted! Total files created: {total_split}")
    print(f"Output directory: {output_base_dir}")

if __name__ == "__main__":
    main()
