from __future__ import annotations

import argparse
import json
import secrets
import sys
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


PROJECT_ROOT = Path(__file__).resolve().parent
REPO_ROOT = PROJECT_ROOT.parent
ROUTER_ROOT = REPO_ROOT / "9router"
RUNTIME_ROOT = PROJECT_ROOT / "runtime"
STACK_STATE_PATH = RUNTIME_ROOT / "9router_stack.json"
ROUTER_DATA_DIR = RUNTIME_ROOT / "9router_data"
ROUTER_DB_PATH = ROUTER_DATA_DIR / "db.json"
ROUTER_ENV_PATH = ROUTER_ROOT / ".env.local"

AZURE_PROVIDER_NODE_ID = "anthropic-compatible-azure-local-proxy"
AZURE_PROVIDER_PREFIX = "azproxy"
AZURE_PROVIDER_NAME = "Azure Local Proxy"
AZURE_CONNECTION_NAME = "Azure via Local Proxy"
GLM_CONNECTION_NAME = "GLM Native"
ROUTER_API_KEY_NAME = "azure-anthropic-sdk-local-router"


def utc_now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def ensure_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def read_env_file(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.exists():
        return values
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip().strip('"').strip("'")
    return values


def load_json(path: Path, fallback: Any) -> Any:
    if not path.exists():
        return fallback
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return fallback


def default_db() -> dict[str, Any]:
    return {
        "providerConnections": [],
        "providerNodes": [],
        "proxyPools": [],
        "modelAliases": {},
        "mitmAlias": {},
        "combos": [],
        "apiKeys": [],
        "settings": {
            "cloudEnabled": False,
            "tunnelEnabled": False,
            "tunnelUrl": "",
            "stickyRoundRobinLimit": 3,
            "providerStrategies": {},
            "comboStrategy": "fallback",
            "comboStrategies": {},
            "requireLogin": False,
            "requireApiKey": True,
            "observabilityEnabled": True,
            "observabilityMaxRecords": 1000,
            "observabilityBatchSize": 20,
            "observabilityFlushIntervalMs": 5000,
            "observabilityMaxJsonSize": 1024,
            "outboundProxyEnabled": False,
            "outboundProxyUrl": "",
            "outboundNoProxy": "",
            "mitmRouterBaseUrl": "http://localhost:20128",
        },
        "pricing": {},
    }


def normalized_windows_path(path: Path) -> str:
    return path.resolve().as_posix()


def build_env_local(
    *,
    router_port: int,
    data_dir: Path,
    base_url: str,
    jwt_secret: str,
    initial_password: str,
    api_key_secret: str,
    machine_id_salt: str,
) -> str:
    return "\n".join(
        [
            "# Generated by azure_anthropic_sdk/bootstrap_9router_stack.py",
            f"JWT_SECRET={jwt_secret}",
            f"INITIAL_PASSWORD={initial_password}",
            f"DATA_DIR={normalized_windows_path(data_dir)}",
            f"PORT={router_port}",
            "NODE_ENV=development",
            f"BASE_URL={base_url}",
            f"NEXT_PUBLIC_BASE_URL={base_url}",
            f"API_KEY_SECRET={api_key_secret}",
            f"MACHINE_ID_SALT={machine_id_salt}",
            "ENABLE_REQUEST_LOGS=false",
            "OBSERVABILITY_ENABLED=true",
            "AUTH_COOKIE_SECURE=false",
            "REQUIRE_API_KEY=true",
            "",
        ]
    )


def upsert_provider_node(db: dict[str, Any], *, base_url: str, now: str) -> None:
    nodes = db.setdefault("providerNodes", [])
    for node in nodes:
        if node.get("id") == AZURE_PROVIDER_NODE_ID:
            node.update(
                {
                    "type": "anthropic-compatible",
                    "name": AZURE_PROVIDER_NAME,
                    "prefix": AZURE_PROVIDER_PREFIX,
                    "baseUrl": base_url,
                    "updatedAt": now,
                }
            )
            return
    nodes.append(
        {
            "id": AZURE_PROVIDER_NODE_ID,
            "type": "anthropic-compatible",
            "name": AZURE_PROVIDER_NAME,
            "prefix": AZURE_PROVIDER_PREFIX,
            "baseUrl": base_url,
            "createdAt": now,
            "updatedAt": now,
        }
    )


def upsert_provider_connection(
    db: dict[str, Any],
    *,
    provider: str,
    name: str,
    api_key: str,
    now: str,
    default_model: str | None = None,
    provider_specific_data: dict[str, Any] | None = None,
) -> None:
    connections = db.setdefault("providerConnections", [])
    for connection in connections:
        if (
            connection.get("provider") == provider
            and connection.get("authType") == "apikey"
            and connection.get("name") == name
        ):
            connection.update(
                {
                    "apiKey": api_key,
                    "defaultModel": default_model,
                    "providerSpecificData": provider_specific_data or {},
                    "isActive": True,
                    "priority": 1,
                    "updatedAt": now,
                }
            )
            return

    connection = {
        "id": str(uuid.uuid4()),
        "provider": provider,
        "authType": "apikey",
        "name": name,
        "priority": 1,
        "isActive": True,
        "apiKey": api_key,
        "createdAt": now,
        "updatedAt": now,
    }
    if default_model:
        connection["defaultModel"] = default_model
    if provider_specific_data:
        connection["providerSpecificData"] = provider_specific_data
    connections.append(connection)


def upsert_combo(db: dict[str, Any], *, name: str, models: list[str], now: str) -> None:
    combos = db.setdefault("combos", [])
    for combo in combos:
        if combo.get("name") == name:
            combo.update({"models": models, "updatedAt": now})
            return
    combos.append(
        {
            "id": str(uuid.uuid4()),
            "name": name,
            "models": models,
            "createdAt": now,
            "updatedAt": now,
        }
    )


def upsert_api_key(db: dict[str, Any], *, key_name: str, key_value: str, now: str) -> None:
    api_keys = db.setdefault("apiKeys", [])
    for item in api_keys:
        if item.get("name") == key_name:
            item.update({"key": key_value, "isActive": True})
            return
    api_keys.append(
        {
            "id": str(uuid.uuid4()),
            "name": key_name,
            "key": key_value,
            "machineId": "azure-anthropic-sdk-local",
            "isActive": True,
            "createdAt": now,
        }
    )


def main() -> int:
    parser = argparse.ArgumentParser(description="Bootstrap 9router stack for Azure local proxy and GLM native.")
    parser.add_argument("--router-port", type=int, default=None)
    parser.add_argument("--azure-proxy-port", type=int, default=None)
    parser.add_argument("--router-api-key", default=None)
    args = parser.parse_args()

    if not ROUTER_ROOT.exists():
        print(f"9router repo not found: {ROUTER_ROOT}", file=sys.stderr)
        return 1

    ensure_dir(RUNTIME_ROOT)
    ensure_dir(ROUTER_DATA_DIR)

    env_values = read_env_file(PROJECT_ROOT / ".env")
    state = load_json(STACK_STATE_PATH, {})

    proxy_port = args.azure_proxy_port or int(env_values.get("PROXY_PORT", "8009"))
    router_port = args.router_port or int(env_values.get("ROUTER_PORT", "20128"))
    router_base_url = f"http://127.0.0.1:{router_port}"
    azure_proxy_messages_base_url = f"http://127.0.0.1:{proxy_port}/v1"

    jwt_secret = state.get("jwt_secret") or secrets.token_urlsafe(32)
    initial_password = state.get("initial_password") or secrets.token_urlsafe(12)
    api_key_secret = state.get("api_key_secret") or secrets.token_urlsafe(24)
    machine_id_salt = state.get("machine_id_salt") or secrets.token_urlsafe(18)
    router_api_key = args.router_api_key or state.get("router_api_key") or ("router-" + secrets.token_urlsafe(24))

    glm_api_key = env_values.get("GLM_API_KEY", "").strip()
    glm_model = env_values.get("GLM_MODEL_NAME", "glm-5").strip() or "glm-5"

    db = load_json(ROUTER_DB_PATH, default_db())
    if not isinstance(db, dict):
        db = default_db()
    now = utc_now()

    upsert_provider_node(db, base_url=azure_proxy_messages_base_url, now=now)
    upsert_provider_connection(
        db,
        provider=AZURE_PROVIDER_NODE_ID,
        name=AZURE_CONNECTION_NAME,
        api_key="local-anthropic-proxy",
        default_model="azure-sonnet",
        now=now,
        provider_specific_data={
            "prefix": AZURE_PROVIDER_PREFIX,
            "baseUrl": azure_proxy_messages_base_url,
            "nodeName": AZURE_PROVIDER_NAME,
        },
    )

    if glm_api_key:
        upsert_provider_connection(
            db,
            provider="glm",
            name=GLM_CONNECTION_NAME,
            api_key=glm_api_key,
            default_model=glm_model,
            now=now,
        )

    aliases = db.setdefault("modelAliases", {})
    aliases["azure-sonnet"] = f"{AZURE_PROVIDER_NODE_ID}/azure-sonnet"
    aliases["azure-opus"] = f"{AZURE_PROVIDER_NODE_ID}/azure-opus"
    if glm_api_key:
        aliases["glm-sonnet"] = f"glm/{glm_model}"
        aliases["glm-opus"] = f"glm/{glm_model}"

    router_sonnet_models = ["azure-sonnet"]
    router_opus_models = ["azure-opus"]
    if glm_api_key:
        router_sonnet_models.append("glm-sonnet")
        router_opus_models.append("glm-opus")

    upsert_combo(db, name="router-sonnet", models=router_sonnet_models, now=now)
    upsert_combo(db, name="router-opus", models=router_opus_models, now=now)
    upsert_api_key(db, key_name=ROUTER_API_KEY_NAME, key_value=router_api_key, now=now)

    settings = db.setdefault("settings", {})
    settings["comboStrategy"] = "fallback"
    settings["comboStrategies"] = {
        **settings.get("comboStrategies", {}),
        "router-sonnet": {"fallbackStrategy": "fallback"},
        "router-opus": {"fallbackStrategy": "fallback"},
    }
    settings["requireApiKey"] = True
    settings["requireLogin"] = False
    settings["observabilityEnabled"] = True
    settings["mitmRouterBaseUrl"] = router_base_url

    ROUTER_DB_PATH.write_text(json.dumps(db, indent=2, ensure_ascii=False), encoding="utf-8")
    ROUTER_ENV_PATH.write_text(
        build_env_local(
            router_port=router_port,
            data_dir=ROUTER_DATA_DIR,
            base_url=router_base_url,
            jwt_secret=jwt_secret,
            initial_password=initial_password,
            api_key_secret=api_key_secret,
            machine_id_salt=machine_id_salt,
        ),
        encoding="utf-8",
    )

    next_state = {
        "generated_at": now,
        "router_root": str(ROUTER_ROOT.resolve()),
        "router_env_path": str(ROUTER_ENV_PATH.resolve()),
        "router_db_path": str(ROUTER_DB_PATH.resolve()),
        "router_data_dir": str(ROUTER_DATA_DIR.resolve()),
        "router_base_url": router_base_url,
        "router_port": router_port,
        "router_api_key": router_api_key,
        "router_api_key_name": ROUTER_API_KEY_NAME,
        "router_sonnet_model": "router-sonnet",
        "router_opus_model": "router-opus",
        "azure_proxy_base_url": f"http://127.0.0.1:{proxy_port}",
        "azure_proxy_messages_base_url": azure_proxy_messages_base_url,
        "azure_provider_node_id": AZURE_PROVIDER_NODE_ID,
        "glm_available": bool(glm_api_key),
        "glm_model_name": glm_model,
        "jwt_secret": jwt_secret,
        "initial_password": initial_password,
        "api_key_secret": api_key_secret,
        "machine_id_salt": machine_id_salt,
    }
    STACK_STATE_PATH.write_text(json.dumps(next_state, indent=2, ensure_ascii=False), encoding="utf-8")

    print(f"Bootstrapped 9router stack at {router_base_url}")
    print(f"Router env: {ROUTER_ENV_PATH}")
    print(f"Router db: {ROUTER_DB_PATH}")
    print(f"Azure upstream: {azure_proxy_messages_base_url}")
    print(f"GLM available: {bool(glm_api_key)}")
    print(f"Stack state: {STACK_STATE_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
