from pathlib import Path


BASE_DIR = Path(__file__).resolve().parent.parent
ROOT_DIR = BASE_DIR.parent
WORKSPACES_DIR = BASE_DIR / "workspaces"
DOCS_DIR = BASE_DIR / "docs"
ARCHITECTURE_DOCS_DIR = DOCS_DIR / "architecture"
LOGS_DIR = BASE_DIR / "logs"
DATA_DIR = BASE_DIR / "data"
CONFIG_DIR = BASE_DIR / "config"
TEMPLATES_DIR = BASE_DIR / "templates"
UPLOADS_DIR = DATA_DIR / "uploads"
RUNS_DIR = DATA_DIR / "pipeline_runs"
EXTRACTED_TEXT_DIR = DATA_DIR / "extracted_text"
REPORTS_DIR = DATA_DIR / "reports"
DATA_VIEW_DIR = DATA_DIR / "data_view"
DATA_SCRIPT_DIR = DATA_DIR / "script"
CLAUDE_BRIDGE_DIR = DATA_DIR / "claude_bridge"
CLAUDE_BRIDGE_INTERACTIONS_DIR = CLAUDE_BRIDGE_DIR / "interactions"
CLAUDE_BRIDGE_FEEDBACK_DIR = CLAUDE_BRIDGE_DIR / "feedback"
KNOWLEDGE_REGISTRY_DIR = DATA_DIR / "knowledge_registry"
KNOWLEDGE_REGISTRY_PATH = KNOWLEDGE_REGISTRY_DIR / "knowledge_registry.json"
KNOWLEDGE_MANIFESTS_DIR = KNOWLEDGE_REGISTRY_DIR / "manifests"
KNOWLEDGE_SNAPSHOTS_DIR = KNOWLEDGE_REGISTRY_DIR / "snapshots"
KNOWLEDGE_EXCEL_VIEWS_DIR = KNOWLEDGE_REGISTRY_DIR / "views"
KNOWLEDGE_TEXT_VIEWS_DIR = KNOWLEDGE_REGISTRY_DIR / "text_views"
KNOWLEDGE_ASSETS_DIR = KNOWLEDGE_REGISTRY_DIR / "assets"
KNOWLEDGE_PROTOCOL_PDFS_DIR = KNOWLEDGE_ASSETS_DIR / "protocol_pdfs"
KNOWLEDGE_PROTOCOL_TEXTS_DIR = KNOWLEDGE_ASSETS_DIR / "protocol_texts"
KNOWLEDGE_INSURANCE_RULES_DIR = KNOWLEDGE_ASSETS_DIR / "insurance_rulebooks"
KNOWLEDGE_BENEFIT_TABLES_DIR = KNOWLEDGE_ASSETS_DIR / "benefit_tables"
KNOWLEDGE_LEGAL_DOCS_DIR = KNOWLEDGE_ASSETS_DIR / "legal_documents"
KNOWLEDGE_SERVICE_TABLES_DIR = KNOWLEDGE_ASSETS_DIR / "service_tables"
KNOWLEDGE_SYMPTOM_TABLES_DIR = KNOWLEDGE_ASSETS_DIR / "symptom_tables"
KNOWLEDGE_BENCHMARKS_DIR = KNOWLEDGE_ASSETS_DIR / "benchmarks"
KNOWLEDGE_MEMORY_DIR = KNOWLEDGE_ASSETS_DIR / "memory"
KNOWLEDGE_MISC_DIR = KNOWLEDGE_ASSETS_DIR / "misc"
KNOWLEDGE_GUIDES_DIR = KNOWLEDGE_REGISTRY_DIR / "guides"
KNOWLEDGE_DOMAIN_GUIDES_DIR = KNOWLEDGE_GUIDES_DIR / "domains"
KNOWLEDGE_DISEASE_GUIDES_DIR = KNOWLEDGE_GUIDES_DIR / "diseases"
KNOWLEDGE_ASSET_GUIDES_DIR = KNOWLEDGE_GUIDES_DIR / "assets"
DATATEST_DIR = DATA_DIR / "datatest"
DATATEST_CASES_DIR = DATATEST_DIR / "cases"
DATATEST_DATASETS_DIR = DATATEST_DIR / "datasets"
DATATEST_REPORTS_DIR = DATATEST_DIR / "reports"
DATATEST_ASSETS_DIR = DATATEST_DIR / "assets"
DATATEST_SOURCE_DOCS_DIR = DATATEST_DIR / "source_docs"
DATATEST_V02_DIR = DATA_DIR / "datatest_v02"
DATATEST_V03_DIR = DATA_DIR / "datatest_v03"
EXPERIENCE_MEMORY_DIR = DATA_SCRIPT_DIR / "experience_memory"
TESTCASE_TRACE_RUNS_DIR = DATA_SCRIPT_DIR / "testcase_trace_runs"
INGEST_CONFIGS_DIR = CONFIG_DIR / "ingest_configs"
REFERENCE_PDFS_DIR = BASE_DIR / "assets" / "reference_pdfs"
MEDICAL_PIPELINE_SCRIPTS_DIR = BASE_DIR / "medical_pipeline_agent" / "scripts"
CLAIMS_INSIGHTS_DIR = WORKSPACES_DIR / "claims_insights"
CLAIMS_INSIGHTS_CLAIMS_DIR = CLAIMS_INSIGHTS_DIR / "01_claims"
CLAIMS_INSIGHTS_REPORTS_DIR = CLAIMS_INSIGHTS_DIR / "04_reports"
CLAIMS_INSIGHTS_REFERENCE_DIR = CLAIMS_INSIGHTS_DIR / "05_reference"
CLAIMS_INSIGHTS_INSURANCE_DIR = CLAIMS_INSIGHTS_DIR / "06_insurance"
PATHWAY_DATA_ARCHITECTURE_SPEC_PATH = CONFIG_DIR / "pathway_data_architecture_v1.json"
PATHWAY_DATA_ARCHITECTURE_DOC_PATH = ARCHITECTURE_DOCS_DIR / "pathway_data_architecture.md"
CRAWLER_SCRIPT = ROOT_DIR / "scripts" / "crawlers" / "vn_crawler.py"
LEGACY_CRAWLER_SCRIPT = ROOT_DIR / "vn_crawler.py"


def ensure_datatest_layout() -> None:
    for path in (
        DATATEST_DIR,
        DATATEST_CASES_DIR,
        DATATEST_DATASETS_DIR,
        DATATEST_REPORTS_DIR,
        DATATEST_ASSETS_DIR,
        DATATEST_SOURCE_DOCS_DIR,
    ):
        path.mkdir(parents=True, exist_ok=True)


def ensure_pathway_data_layout() -> None:
    for path in (
        LOGS_DIR,
        DATA_DIR,
        UPLOADS_DIR,
        RUNS_DIR,
        EXTRACTED_TEXT_DIR,
        REPORTS_DIR,
        DATA_VIEW_DIR,
        DATA_SCRIPT_DIR,
        CLAUDE_BRIDGE_DIR,
        CLAUDE_BRIDGE_INTERACTIONS_DIR,
        CLAUDE_BRIDGE_FEEDBACK_DIR,
        KNOWLEDGE_REGISTRY_DIR,
        KNOWLEDGE_MANIFESTS_DIR,
        KNOWLEDGE_SNAPSHOTS_DIR,
        KNOWLEDGE_EXCEL_VIEWS_DIR,
        KNOWLEDGE_TEXT_VIEWS_DIR,
        KNOWLEDGE_ASSETS_DIR,
        KNOWLEDGE_PROTOCOL_PDFS_DIR,
        KNOWLEDGE_PROTOCOL_TEXTS_DIR,
        KNOWLEDGE_INSURANCE_RULES_DIR,
        KNOWLEDGE_BENEFIT_TABLES_DIR,
        KNOWLEDGE_LEGAL_DOCS_DIR,
        KNOWLEDGE_SERVICE_TABLES_DIR,
        KNOWLEDGE_SYMPTOM_TABLES_DIR,
        KNOWLEDGE_BENCHMARKS_DIR,
        KNOWLEDGE_MEMORY_DIR,
        KNOWLEDGE_MISC_DIR,
        KNOWLEDGE_GUIDES_DIR,
        KNOWLEDGE_DOMAIN_GUIDES_DIR,
        KNOWLEDGE_DISEASE_GUIDES_DIR,
        KNOWLEDGE_ASSET_GUIDES_DIR,
        EXPERIENCE_MEMORY_DIR,
        TESTCASE_TRACE_RUNS_DIR,
        INGEST_CONFIGS_DIR,
        ARCHITECTURE_DOCS_DIR,
    ):
        path.mkdir(parents=True, exist_ok=True)
    ensure_datatest_layout()
